name: CI/CD Deployment to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install LFTP
        run: sudo apt-get install -y lftp

      - name: Debug Connection Variables
        run: |
          echo "FTP_HOST=${{ secrets.CPANEL_HOST }}"
          echo "FTP_USERNAME=${{ secrets.CPANEL_USERNAME }}"
          echo "FTP_PASSWORD is set" 

      - name: Deploy
        env:
          FTP_HOST: ${{ secrets.CPANEL_HOST }}
          FTP_USERNAME: ${{ secrets.CPANEL_USERNAME }}
          FTP_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
        run: |
          lftp -c "
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --reverse --delete --verbose ./ /home/tcssoftt/testing.tcssofttech.com;
          bye
          "
