name: CI/CD Deployment to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install LFTP
        run: sudo apt-get install -y lftp

      - name: Deploy to cPanel
        env:
          FTP_HOST: ${{ secrets.CPANEL_HOST }}
          FTP_USERNAME: ${{ secrets.CPANEL_USERNAME }}
          FTP_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
        run: |
          lftp -e "
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
          mirror --reverse --delete --verbose ./ /path/to/testing.tcssofttech.com/directory
          bye
          "
